#!/bin/sh

# Use aliases with sudo commands
alias sudo="sudo "

# Place wget history in XDG data directory
alias wget=wget --hsts-file="$XDG_DATA_HOME/wget-hsts"

# Use colorized commands
alias \
    ls="ls --color=auto --group-directories-first" \
    grep="grep --color=auto" \
    egrep="egrep --color=auto" \
    fgrep="fgrep --color=auto"

# Use neovim in place of vim
if command -v nvim > /dev/null 2>&1; then
    alias vim="nvim" vimdiff="nvim -d"
fi

alias ssh="TERM=xterm-256color ssh"

# Open nnn
alias n3="nnn -de"

# Handle dotfile tracking
alias config='git --git-dir=$HOME/Git/.dotfiles/ --work-tree=$HOME'
