#!/bin/sh

# Use aliases with sudo commands
alias sudo="sudo "

# Place wget history in XDG data directory
alias wget=wget --hsts-file="$XDG_DATA_HOME/wget-hsts"

# Use colorized commands
alias \
    ls="ls --color=auto --group-directories-first" \
    grep="grep --color=auto" \
    egrep="egrep --color=auto" \
    fgrep="fgrep --color=auto"

# Use neovim in place of vim
[ -x "$(command -v nvim)" ] \
    && alias vim="nvim" vimdiff="nvim -d"

if command -v bat > /dev/null 2>&1; then
  export MANPAGER="sh -c 'col -bx | bat -l man -p'"
  export MANROFFOPT="-c"
  export BAT_THEME="base16"
  alias cat="bat --paging=never"
  alias less="bat --paging=always"
fi

# Open nnn
alias n3="nnn -de"

# Clear terminal and run neofetch
alias fetch="clear && neofetch"

# Handle dotfile tracking
alias config='/usr/bin/git --git-dir=$HOME/Git/.dotfiles/ --work-tree=$HOME'
