#!/bin/sh

# Default programs
export BROWSER="firefox"
export EDITOR="nvim"
export VISUAL="$HOME/Scripts/vimsplit"
export PAGER="less"
export AUR_PAGER="nnn"

# XDG user directories
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

# XDG system directories
export XDG_DATA_DIRS="/usr/local/share:/usr/share"
export XDG_CONFIG_DIRS="/etc/xdg"

# Add ~/.local/bin to path
case "$PATH" in
  *"$HOME/.local/bin"*) ;;
  *) export PATH="$PATH:$HOME/.local/bin" ;;
esac

# Home directory clean-up
export ZDOTDIR=$XDG_CONFIG_HOME/zsh

# Sort hidden files on top
export LC_COLLATE="C"

# Pfetch configuration
export PF_INFO="ascii title os kernel memory uptime shell editor palette"
