#!/bin/sh

# Default programs
export BROWSER="floorp"
export EDITOR="nvim"
export VISUAL="nvim"
export PAGER="less"
export AUR_PAGER="nnn"

# Application theme
export GTK_THEME="Catppuccin-Macchiato-Standard-Lavender-Dark"
export QT_STYLE_OVERRIDE="kvantum"

# XDG user directories
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

# Add ~/.local/bin to path
case "$PATH" in
    *"$HOME/.local/bin"*) ;;
    *) export PATH="$PATH:$HOME/.local/bin" ;;
esac

# Home directory clean-up
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export MAMBARC="$XDG_CONFIG_HOME/conda/condarc"

# Sort hidden files on top
export LC_COLLATE="C"

# Pfetch configuration
export PF_INFO="ascii title os kernel memory uptime shell editor palette"

# Run firefox in wayland mode
if [ "$XDG_SESSION_TYPE" = "wayland" ]; then
    export MOZ_ENABLE_WAYLAND=1
fi

# Krita theme
export KRITA_NO_STYLE_OVERRIDE=1
